# Generated by Django 2.0.7 on 2019-12-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20191230_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_created',
            new_name='time_created',
        ),
    ]
