# Generated by Django 2.0.7 on 2019-12-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20191230_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='time_created',
            new_name='date_created',
        ),
    ]
